services:
  - type: web
    name: crop-recommendation-system
    env: python
    buildCommand: pip install -r requirements.txt
    run: pip install --upgrade pip
    startCommand: gunicorn -w 4 run:app
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
